# ===================================================  #
# Project: hurlaz
# ===================================================  #
name: Test Hurlaz Action
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. checkout the codebase
      - name: checkout codebase
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: build the project
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: install deps
        run: npm ci
      - name: build project
        run: npm run build
      - name: commit build output
        run: "git config user.name \"github-actions[bot]\"\ngit config user.email \"github-actions[bot]@noreply.github.com\"\ngit add .\nif git diff --cached --quiet; then \n  echo \"No Changes\" \n  exit 0\nfi \ngit commit -m \"chore: update bundle [skip ci]\"\ngit push"
